package dev.ip.projekt.service;

import dev.ip.projekt.model.dto.BookingRequestDTO;
import dev.ip.projekt.model.dto.BookingResponseDTO;
import dev.ip.projekt.model.entity_new.CustomerAccount;
import dev.ip.projekt.model.entity_new.Flight;
import dev.ip.projekt.model.entity_new.Reservation;
import dev.ip.projekt.repository.AirportRepository;
import dev.ip.projekt.repository.CustomerAccountRepository;
import dev.ip.projekt.repository.FlightRepository;
import dev.ip.projekt.repository.ReservationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Random;
import java.util.stream.Collectors;

@Service
public class BookingService {

    @Autowired
    private ReservationRepository reservationRepository;

    @Autowired
    private FlightRepository flightRepository;

    @Autowired
    private AirportRepository airportRepository;

    @Autowired
    private CustomerAccountRepository customerAccountRepository;

    @Transactional
    public BookingResponseDTO createBooking(BookingRequestDTO request, String userEmail) {
        // Find the user's account
        CustomerAccount account = customerAccountRepository.findByEmail(userEmail)
                .orElseThrow(() -> new RuntimeException("User account not found"));

        // Find the flight
        Flight flight = flightRepository.findById(request.getFlightId())
                .orElseThrow(() -> new RuntimeException("Flight not found"));

        // Check if flight is not cancelled
        if (flight.getCancellationStatus() != null && flight.getCancellationStatus() != 0) {
            throw new RuntimeException("Flight is cancelled and cannot be booked");
        }

        // Check if flight date is in the future
        if (flight.getFlightDate().isBefore(LocalDate.now())) {
            throw new RuntimeException("Cannot book a flight in the past");
        }

        // Create new reservation
        Reservation reservation = new Reservation();
        
        // ID is auto-generated by the database
        reservation.setAccountId(account.getAccountId());
        reservation.setFlightId(request.getFlightId());
        reservation.setFareId(request.getFareId() != null ? request.getFareId() : 1); // Default fare if not specified
        reservation.setReservationStatus("Confirmed");
        reservation.setCreationDate(LocalDate.now());
        reservation.setModificationDate(LocalDate.now());
        reservation.setTotalPrice(request.getTotalPrice() != null ? request.getTotalPrice() : BigDecimal.valueOf(100.00));
        reservation.setReservationCode(generateReservationCode());
        reservation.setLuggage(request.getLuggage() != null ? request.getLuggage() : "Standard");
        reservation.setSeat(request.getSeat() != null ? request.getSeat() : generateSeat());
        reservation.setTicketNumber(generateTicketNumber());
        reservation.setTicketStatus("Issued");

        // Save the reservation
        Reservation savedReservation = reservationRepository.save(reservation);

        // Build response
        return buildBookingResponse(savedReservation, flight, request.getPassengerName(), request.getPassengerEmail());
    }

    public List<BookingResponseDTO> getMyBookings(String userEmail) {
        CustomerAccount account = customerAccountRepository.findByEmail(userEmail)
                .orElseThrow(() -> new RuntimeException("User account not found"));

        List<Reservation> reservations = reservationRepository.findByAccountIdOrderByCreationDateDesc(account.getAccountId());

        return reservations.stream()
                .map(this::convertToBookingResponse)
                .collect(Collectors.toList());
    }

    @Transactional
    public BookingResponseDTO cancelBooking(Long reservationId, String userEmail) {
        CustomerAccount account = customerAccountRepository.findByEmail(userEmail)
                .orElseThrow(() -> new RuntimeException("User account not found"));

        Reservation reservation = reservationRepository.findById(reservationId)
                .orElseThrow(() -> new RuntimeException("Reservation not found"));

        // Check if the reservation belongs to the user
        if (!reservation.getAccountId().equals(account.getAccountId())) {
            throw new RuntimeException("You are not authorized to cancel this reservation");
        }

        // Check if reservation can be cancelled
        if ("Cancelled".equals(reservation.getReservationStatus())) {
            throw new RuntimeException("Reservation is already cancelled");
        }

        // Update reservation status
        reservation.setReservationStatus("Cancelled");
        reservation.setModificationDate(LocalDate.now());
        reservation.setTicketStatus("Cancelled");

        Reservation updatedReservation = reservationRepository.save(reservation);

        return convertToBookingResponse(updatedReservation);
    }

    private BookingResponseDTO buildBookingResponse(Reservation reservation, Flight flight, String passengerName, String passengerEmail) {
        BookingResponseDTO response = new BookingResponseDTO();
        
        response.setReservationId(reservation.getReservationId());
        response.setReservationCode(reservation.getReservationCode());
        response.setReservationStatus(reservation.getReservationStatus());
        response.setCreationDate(reservation.getCreationDate());
        response.setTotalPrice(reservation.getTotalPrice());
        response.setSeat(reservation.getSeat());
        response.setLuggage(reservation.getLuggage());
        response.setTicketNumber(reservation.getTicketNumber());
        response.setPassengerName(passengerName);
        response.setPassengerEmail(passengerEmail);

        // Flight info
        response.setFlightId(flight.getFlightId());
        response.setFlightNumber(String.valueOf(flight.getFlightNumber()));
        response.setFlightDate(flight.getFlightDate());
        response.setDepartureAirportId(flight.getStartAirport());
        response.setArrivalAirportId(flight.getEndAirport());
        
        // Get airport details
        airportRepository.findById(flight.getStartAirport()).ifPresent(airport -> {
            response.setDepartureCity(airport.getCity());
        });
        airportRepository.findById(flight.getEndAirport()).ifPresent(airport -> {
            response.setArrivalCity(airport.getCity());
        });

        // Format times
        response.setDepartureTime(formatTime(flight.getScheduledDeparture()));
        response.setArrivalTime(formatTime(flight.getScheduledArrival()));

        return response;
    }

    private BookingResponseDTO convertToBookingResponse(Reservation reservation) {
        BookingResponseDTO response = new BookingResponseDTO();
        
        response.setReservationId(reservation.getReservationId());
        response.setReservationCode(reservation.getReservationCode());
        response.setReservationStatus(reservation.getReservationStatus());
        response.setCreationDate(reservation.getCreationDate());
        response.setTotalPrice(reservation.getTotalPrice());
        response.setSeat(reservation.getSeat());
        response.setLuggage(reservation.getLuggage());
        response.setTicketNumber(reservation.getTicketNumber());

        // Get flight info
        flightRepository.findById(reservation.getFlightId()).ifPresent(flight -> {
            response.setFlightId(flight.getFlightId());
            response.setFlightNumber(String.valueOf(flight.getFlightNumber()));
            response.setFlightDate(flight.getFlightDate());
            response.setDepartureAirportId(flight.getStartAirport());
            response.setArrivalAirportId(flight.getEndAirport());
            response.setDepartureTime(formatTime(flight.getScheduledDeparture()));
            response.setArrivalTime(formatTime(flight.getScheduledArrival()));

            // Get airport details
            airportRepository.findById(flight.getStartAirport()).ifPresent(airport -> {
                response.setDepartureCity(airport.getCity());
            });
            airportRepository.findById(flight.getEndAirport()).ifPresent(airport -> {
                response.setArrivalCity(airport.getCity());
            });
        });

        return response;
    }

    private String generateReservationCode() {
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder code = new StringBuilder();
        Random random = new Random();
        for (int i = 0; i < 6; i++) {
            code.append(chars.charAt(random.nextInt(chars.length())));
        }
        return code.toString();
    }

    private String generateTicketNumber() {
        String chars = "0123456789";
        StringBuilder number = new StringBuilder("TKT");
        Random random = new Random();
        for (int i = 0; i < 10; i++) {
            number.append(chars.charAt(random.nextInt(chars.length())));
        }
        return number.toString();
    }

    private String generateSeat() {
        Random random = new Random();
        int row = random.nextInt(30) + 1;
        char seat = (char) ('A' + random.nextInt(6));
        return row + String.valueOf(seat);
    }

    private String formatTime(Integer minutes) {
        if (minutes == null) return null;
        int hours = minutes / 60;
        int mins = minutes % 60;
        return String.format("%02d:%02d", hours, mins);
    }
}
